### ISSUE TITLE
don't have modual  '.acc_preresnet  '

### ISSUE THREAD

**Issue by xfdywy** [D-X-Y/ResNeXt#1]
If I run the code, I got ' No module named 'models.acc_preresnet''
In __init__.py of models, there is 

                from .acc_preresnet import accpreresnet20, accpreresnet32, accpreresnet44, accpreresnet56

but the code seems not contain the acc_preresnet.py

**Comment by D-X-Y** [comment]
Thanks for reminder, this is a removed model but I forget to remove it from the __init__.py
I have already fixed this bug.
